version: '3.8'

services:
  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=MySQL@09
      - MYSQL_DATABASE=chatapp
      - MYSQL_USER=root
      - MYSQL_PASSWORD=MySQL@09

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql_db
      - MYSQL_ROOT_PASSWORD=MySQL@09

volumes:
  mysql_data: {}
